### ISSUE TITLE
BLE LE_Coded Phy - 15m range on ARDUINO NANO 33 BLE

### ISSUE THREAD

**Issue by cabotm** [tjpetz/mbed_BLE_GAP_advertiser#1]
Using these parameters (for scanning and advertising) don't really work.

Are you sure it is really a BLE5.0 le coded phy?

**Comment by tjpetz** [comment]
@cabotm to the best of my ability I believe I'm seeing coded phy.  When I use my scanner program on the Nano 33 and configure it to only scan on coded it sees nothing in my environment (because nothing else I have seems to have coded phy) and when I turn on this code and configure it to advertise only on coded phy the scan sees this board.  Nothing else I have that scans (again no coded why support) sees it.

What errors are other indications are you seeing that suggest it's not coded?

**Comment by cabotm** [comment]
Hi Thomas,

I start working on ble5.0 le codes 3 months ago, and have the same code than your code. I think that the render distance problem is because European legislation..

________________________________
De : Thomas J. Petz, Jr. ***@***.***>
Envoyé : samedi 24 avril 2021 14:43
À : tjpetz/mbed_BLE_GAP_advertiser ***@***.***>
Cc : cabotm ***@***.***>; Mention ***@***.***>
Objet : Re: [tjpetz/mbed_BLE_GAP_advertiser] BLE LE_Coded Phy - 15m range on ARDUINO NANO 33 BLE (#1)


@cabotm<https://github.com/cabotm> to the best of my ability I believe I'm seeing coded phy. When I use my scanner program on the Nano 33 and configure it to only scan on coded it sees nothing in my environment (because nothing else I have seems to have coded phy) and when I turn on this code and configure it to advertise only on coded phy the scan sees this board. Nothing else I have that scans (again no coded why support) sees it.

What errors are other indications are you seeing that suggest it's not coded?

**Comment by tjpetz** [comment]
Hi @cabotm,

There are several challenges on range.  I can't say I have any definitive information in this space, but I share my findings and understandings in the hope they may help you.

By default the nRF52840 chip on the Arduino board will transmit at 0dbm.  The standard Arduino BLE library has no ability to control the transmit power.  The chip itself can transmit at powers between 8dbm and -40dbm.  Unfortunately directly using the low level radio interface to set the power doesn't work as both the mbed BLE library and Arduino BLE libraries both reset the TX power to the default.

I started working with the mbed BLE interface because it does allow you set the TX power preference for advertisements, but advertisements only.  I've not yet found an interface to control TX power for connections.  I think this can be done with the Nordic Soft Devices (Nordics S140 soft device is supported on the chip).  However, I've not yet tried using the Nordic soft device as it requires flashing the firmware onto the Arduino (and obviously writing significantly different code as the API is substantially different).  I hope to do this in the future but haven't had time yet.

While I'm confident I'm using Coded PHY on the chip I've not yet done a range test.  Range is so hard to predict because it's so dependent on the environment.  All the advertised ranges are usually in free space (nothing in between the transmitter and the receiver) and done under ideal conditions.  So range in most circumstance will be significantly less than what the manufacture claims.

I'm not sure what the European limits are on TX power.  I'm in the US and I have verified I can, with the mbedOS BLE API, advertise at what appears to be the max of 8 dbm.  While I've not verified this in range tests I can verify that increasing the TX power affects the RSSI as expected for a fixed range.

The other challenge with Coded PHY is that there is very limited support for it.  In fact the only devices I have that can run with the Coded PHY are the Nordic chips on the Arduino.  Raspberry PIs, Macs, and my iPhone do not currently support Coded.  So at this point I've only been trying coded to demonstrate it's possible between the Arduino Nano 33 BLE's.

Finally, please note the code I've posted here only advertises over Coded PHY.  I've not yet had time to experiment with connecting over Coded Phy.  If you attempt to connect with the posted code it's going to fall back to 2M or 1M PHY depending on what's supported by the central device attempting to connect.

I hope this helps.  Good luck getting the range you're hoping for.
