### ISSUE TITLE
Stuck on Advertising Handle  1

### ISSUE THREAD

**Issue by imammashur** [tjpetz/mbed_BLE_GAP_advertiser#2]
Hi @tjpetz 
This repository is very awesome. This is very helpful for me.

Anyway, I would like to ask you that I got stuck after uploading it and test it on my Arduino Nano 33 BLE.

From the serial monitor, I receive 

```
Starting BLEDEVICE MAC ADDRESS: d4:0f:68:9a:59:09
Starting systemMax advertising sets = 3

Advertising started (handle: 0)
Advertising started on handle: 0

Advertising started (handle: 1
Advertising started on handle: 1
```

I have been waiting for around 1 minute and nothing happened. Can you help me with that? Thank you.

**Comment by tjpetz** [comment]
For the transmitting Nano device this is the expected behavior.  You can use an app (on your phone or computer) to scan for BLE advertisers.  I use BlueSee on my Mac and nRF Connect on my iPhone to scan.  When the Nano detects a scan it will report that it received a scan request on the serial monitor.  However, without a scan request there will be no further output from this program.

If you have another Nano BLE you can use the scanner I created https://github.com/tjpetz/mbed_BLE_GAP_scanner to scan.    The advantage to use another Nano BLE is that you can control exactly what is scanned (i.e. 1M, 2M, or Coded only).
